=== ZeraGmbH/zera-classes/modulemanager/json-schemas/logger-configs-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "$defs": {
        "arrentry": {
            "type": "object",
            "required": [ "EntityId" ],
            "properties": {
                "EntityId": {
                    "type": "integer"
                },
                "Comment": {
                    "type": "string"
                },
                "Components": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1
                }
            },
            "additionalProperties": false
        },
        "loggerarray": {
            "type": "array",
            "items": { "$ref": "#/$defs/arrentry" },
            "minItems": 1
        }
    },
    "anyOf": [
        {"required": ["ZeraActualValues"]},
        {"required": ["ZeraHarmonics"]},
        {"required": ["ZeraCurves"]},
        {"required": ["ZeraComparison"]},
        {"required": ["ZeraBurden"]},
        {"required": ["ZeraTransformer"]},
        {"required": ["ZeraDCReference"]},
        {"required": ["ZeraQuartzReference"]},
        {"required": ["ZeraSourceControl"]}
    ],
    "properties": {
        "ZeraActualValues": { "$ref": "#/$defs/loggerarray" },
        "ZeraHarmonics": { "$ref": "#/$defs/loggerarray" },
        "ZeraCurves": { "$ref": "#/$defs/loggerarray" },
        "ZeraComparison": { "$ref": "#/$defs/loggerarray" },
        "ZeraBurden": { "$ref": "#/$defs/loggerarray" },
        "ZeraTransformer": { "$ref": "#/$defs/loggerarray" },
        "ZeraDCReference": { "$ref": "#/$defs/loggerarray" },
        "ZeraQuartzReference": { "$ref": "#/$defs/loggerarray" },
        "ZeraSourceControl": { "$ref": "#/$defs/loggerarray" }
    },
    "additionalProperties": false
}

=== ZeraGmbH/zera-classes/modulemanager/loggerconfigs/mt310s2-meas-session-dev.json
{
    "ZeraActualValues": [
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DFTModule"
        },
        {
            "EntityId": 1110,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1111,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1070,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1071,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1072,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1090,
            "Comment": "PowerModule CED"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1140,
            "Comment": "LambdaModule"
        }
    ],
    "ZeraHarmonics" : [
        {
            "EntityId": 1110,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1060,
            "Comment": "FFTModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1100,
            "Comment": "POWER3Module"
        }
    ],
    "ZeraCurves" : [
        {
            "EntityId": 1120,
            "Comment": "OSCIModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        }
    ],
    "ZeraComparison": [
        {
            "EntityId": 1130,
            "Comment": "SECModule"
        },
        {
            "EntityId": 1131,
            "Comment": "SECModule"
        },
        {
            "EntityId": 1200,
            "Comment": "SEMModule"
        },
        {
            "EntityId": 1210,
            "Comment": "SPMModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DFTModule"
        },
        {
            "EntityId": 1110,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1111,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1070,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1071,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1072,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1090,
            "Comment": "PowerModule CED"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1140,
            "Comment": "LambdaModule"
        }
    ],
    "ZeraBurden": [
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1160,
            "Comment": "BurdenModule"
        },
        {
            "EntityId": 1161,
            "Comment": "BurdenModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1070,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1071,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1072,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DFTModule"
        }
    ],
    "ZeraTransformer": [
        {
            "EntityId": 1170,
            "Comment": "TransformerModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        }
    ]
}

=== ZeraGmbH/zera-classes/zera-modulemanager/loggerconfigs/demo-session1.json
{
    "ZeraActualValues": [
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DFTModule"
        },
        {
            "EntityId": 1110,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1111,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1070,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1071,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1072,
            "Comment": "PowerModule"
        },
        {
            "EntityId": 1090,
            "Comment": "PowerModule CED"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1140,
            "Comment": "LambdaModule"
        }
    ],
    "ZeraHarmonics" : [
        {
            "EntityId": 1110,
            "Comment": "THDNModule"
        },
        {
            "EntityId": 1060,
            "Comment": "FFTModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1100,
            "Comment": "POWER3Module"
        }
    ],
    "ZeraCurves" : [
        {
            "EntityId": 1120,
            "Comment": "OSCIModule"
        },
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        }
    ],
    "ZeraSourceControl": [
        {
            "EntityId": 1300,
            "Comment": "SourceModule"
        }
    ]
}

=== ZeraGmbH/zera-classes/modulemanager/loggerconfigs/mt310s2-emob-session-ac.json
{
    "ZeraActualValues": [
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DftModule"
        },
        {
            "EntityId": 1060,
            "Comment": "FFTModule"
        },
        {
            "EntityId": 1070,
            "Comment": "Power1Module P"
        },
        {
            "EntityId": 1071,
            "Comment": "Power1Module Q"
        },
        {
            "EntityId": 1072,
            "Comment": "Power1Module S"
        },
        {
            "EntityId": 1140,
            "Comment": "LambdaModule"
        }
    ],
    "ZeraHarmonics" : [
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1060,
            "Comment": "FFTModule"
        },
        {
            "EntityId": 1110,
            "Comment": "THDNModule1"
        },
        {
            "EntityId": 1111,
            "Comment": "THDNModule2"
        }
    ],
    "ZeraCurves" : [
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1120,
            "Comment": "OSCIModule"
        }
    ],
    "ZeraComparison": [
        {
            "EntityId": 1020,
            "Comment": "RangeModule"
        },
        {
            "EntityId": 1040,
            "Comment": "RMSModule"
        },
        {
            "EntityId": 1050,
            "Comment": "DFTModule"
        },
        {
            "EntityId": 1070,
            "Comment": "Power1Module P"
        },
        {
            "EntityId": 1071,
            "Comment": "Power1Module Q"
        },
        {
            "EntityId": 1072,
            "Comment": "Power1Module S"
        },
        {
            "EntityId": 1110,
            "Comment": "THDNModule1"
        },
        {
            "EntityId": 1111,
            "Comment": "THDNModule2"
        },
        {
            "EntityId": 1130,
            "Comment": "SECModule"
        },
        {
            "EntityId": 1140,
            "Comment": "LambdaModule"
        },
        {
            "EntityId": 1200,
            "Comment": "SEMModule"
        },
        {
            "EntityId": 1800,
            "Comment": "RecorderModule"
        }
    ]
}
